// Code generated by SQLBoiler 4.4.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Feeds            string
	Interests        string
	SchemaMigrations string
	Sources          string
	Updates          string
	Users            string
}{
	Feeds:            "feeds",
	Interests:        "interests",
	SchemaMigrations: "schema_migrations",
	Sources:          "sources",
	Updates:          "updates",
	Users:            "users",
}
